TRABAJAMOS CON EL ARCHIVO ITEMS

1-Importamos las librerias a utilizar

In [1]:
import pandas as pd
import json
import ast

2-Abrimos el archivo en formato json

In [2]:
# Ruta al dataset australian_user_reviews
items = 'D:/escritorio/STEAM/Json/australian_users_items.json'

# Se lee de cada línea del dataset
filas_items = []
with open(items) as f:
    for line in f.readlines():
        filas_items.append(ast.literal_eval(line))

# Se convierte en dataframe
df_items = pd.DataFrame(filas_items)
df_items

,user_id,items_count,steam_id,user_url,items
0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
1,js41637,888,76561198035864385,http://steamcommunity.com/id/js41637,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
2,evcentric,137,76561198007712555,http://steamcommunity.com/id/evcentric,"[{'item_id': '1200', 'item_name': 'Red Orchest..."
3,Riot-Punch,328,76561197963445855,http://steamcommunity.com/id/Riot-Punch,"[{'item_id': '10', 'item_name': 'Counter-Strik..."
4,doctr,541,76561198002099482,http://steamcommunity.com/id/doctr,"[{'item_id': '300', 'item_name': 'Day of Defea..."
...,...,...,...,...,...
88305,76561198323066619,22,76561198323066619,http://steamcommunity.com/profiles/76561198323...,"[{'item_id': '413850', 'item_name': 'CS:GO Pla..."
88306,76561198326700687,177,76561198326700687,http://steamcommunity.com/profiles/76561198326...,"[{'item_id': '11020', 'item_name': 'TrackMania..."
88307,XxLaughingJackClown77xX,0,76561198328759259,http://steamcommunity.com/id/XxLaughingJackClo...,[]
88308,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...,"[{'item_id': '304930', 'item_name': 'Unturned'..."
88309,edward_tremethick,0,76561198331598578,http://steamcommunity.com/id/edward_tremethick,[]

REALIZAMOS TRATAMIENTOS A LA COLUMNAS ITEMS

In [3]:
# se normaliza la columna 'items'
df_items2 = pd.json_normalize(filas_items, record_path=['items'], meta=['steam_id','items_count','user_id', 'user_url'] )
df_items2

,item_id,item_name,playtime_forever,playtime_2weeks,steam_id,items_count,user_id,user_url
0,10,Counter-Strike,6,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
1,20,Team Fortress Classic,0,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
2,30,Day of Defeat,7,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
3,40,Deathmatch Classic,0,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
4,50,Half-Life: Opposing Force,0,0,76561197970982479,277,76561197970982479,http://steamcommunity.com/profiles/76561197970...
...,...,...,...,...,...,...,...,...
5153204,346330,BrainBread 2,0,0,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...
5153205,373330,All Is Dust,0,0,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...
5153206,388490,One Way To Die: Steam Edition,3,3,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...
5153207,521570,You Have 10 Seconds 2,4,4,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...
5153208,519140,Minds Eyes,3,3,76561198329548331,7,76561198329548331,http://steamcommunity.com/profiles/76561198329...

Verificar los valores nulos

In [4]:
# Obtener la cantidad de valores nulos por columna
valores_nulos_por_columna = df_items2.isnull().sum()

# Calcular el porcentaje de valores nulos por columna
total_valores_por_columna = len(df_items2)
porcentaje_valores_nulos_por_columna = (valores_nulos_por_columna / total_valores_por_columna) * 100

# Crear un DataFrame con el formato deseado
resultado_df = pd.DataFrame({
    'nombre_campo': valores_nulos_por_columna.index,
    'no_nulos_%': 100 - porcentaje_valores_nulos_por_columna,
    'nulos_%': porcentaje_valores_nulos_por_columna,
    'nulos': valores_nulos_por_columna
})

# Mostrar el resultado
print(resultado_df)

                      nombre_campo  no_nulos_%  nulos_%  nulos
item_id                    item_id       100.0      0.0      0
item_name                item_name       100.0      0.0      0
playtime_forever  playtime_forever       100.0      0.0      0
playtime_2weeks    playtime_2weeks       100.0      0.0      0
steam_id                  steam_id       100.0      0.0      0
items_count            items_count       100.0      0.0      0
user_id                    user_id       100.0      0.0      0
user_url                  user_url       100.0      0.0      0

Verificamos si hay valores duplicados

In [5]:
# Devuelve los duplicados
duplicados = df_items2.loc[df_items2.duplicated()]
duplicados

,item_id,item_name,playtime_forever,playtime_2weeks,steam_id,items_count,user_id,user_url
164294,20,Team Fortress Classic,5,0,76561198084006094,109,Nikiad,http://steamcommunity.com/id/Nikiad
164295,50,Half-Life: Opposing Force,0,0,76561198084006094,109,Nikiad,http://steamcommunity.com/id/Nikiad
164296,70,Half-Life,0,0,76561198084006094,109,Nikiad,http://steamcommunity.com/id/Nikiad
164297,130,Half-Life: Blue Shift,0,0,76561198084006094,109,Nikiad,http://steamcommunity.com/id/Nikiad
164298,220,Half-Life 2,198,0,76561198084006094,109,Nikiad,http://steamcommunity.com/id/Nikiad
...,...,...,...,...,...,...,...,...
4898223,213670,South Park™: The Stick of Truth™,725,0,76561198080057659,39,76561198080057659,http://steamcommunity.com/profiles/76561198080...
4898224,221910,The Stanley Parable,53,0,76561198080057659,39,76561198080057659,http://steamcommunity.com/profiles/76561198080...
4898225,261030,The Walking Dead: Season Two,253,0,76561198080057659,39,76561198080057659,http://steamcommunity.com/profiles/76561198080...
4898226,273110,Counter-Strike Nexon: Zombies,0,0,76561198080057659,39,76561198080057659,http://steamcommunity.com/profiles/76561198080...
4898227,730,Counter-Strike: Global Offensive,0,0,76561198080057659,39,76561198080057659,http://steamcommunity.com/profiles/76561198080...

Eliminamos los valores duplicados

In [6]:
df_items2 = duplicados.drop_duplicates(keep='first')
df_items2

,item_id,item_name,playtime_forever,playtime_2weeks,steam_id,items_count,user_id,user_url
164294,20,Team Fortress Classic,5,0,76561198084006094,109,Nikiad,http://steamcommunity.com/id/Nikiad
164295,50,Half-Life: Opposing Force,0,0,76561198084006094,109,Nikiad,http://steamcommunity.com/id/Nikiad
164296,70,Half-Life,0,0,76561198084006094,109,Nikiad,http://steamcommunity.com/id/Nikiad
164297,130,Half-Life: Blue Shift,0,0,76561198084006094,109,Nikiad,http://steamcommunity.com/id/Nikiad
164298,220,Half-Life 2,198,0,76561198084006094,109,Nikiad,http://steamcommunity.com/id/Nikiad
...,...,...,...,...,...,...,...,...
4898223,213670,South Park™: The Stick of Truth™,725,0,76561198080057659,39,76561198080057659,http://steamcommunity.com/profiles/76561198080...
4898224,221910,The Stanley Parable,53,0,76561198080057659,39,76561198080057659,http://steamcommunity.com/profiles/76561198080...
4898225,261030,The Walking Dead: Season Two,253,0,76561198080057659,39,76561198080057659,http://steamcommunity.com/profiles/76561198080...
4898226,273110,Counter-Strike Nexon: Zombies,0,0,76561198080057659,39,76561198080057659,http://steamcommunity.com/profiles/76561198080...
4898227,730,Counter-Strike: Global Offensive,0,0,76561198080057659,39,76561198080057659,http://steamcommunity.com/profiles/76561198080...

Eliminamos las siguientes columnas

In [7]:
df_items2.drop(['steam_id','playtime_2weeks','user_url'],axis=1, inplace=True)
df_items2.head()

C:\Users\lautaro\AppData\Local\Temp\ipykernel_5816\1166332341.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_items2.drop(['steam_id','playtime_2weeks','user_url'],axis=1, inplace=True)

,item_id,item_name,playtime_forever,items_count,user_id
164294,20,Team Fortress Classic,5,109,Nikiad
164295,50,Half-Life: Opposing Force,0,109,Nikiad
164296,70,Half-Life,0,109,Nikiad
164297,130,Half-Life: Blue Shift,0,109,Nikiad
164298,220,Half-Life 2,198,109,Nikiad

GUARDAMOS EL ARCHIVO EN FORMATO PARQUET

In [8]:
df_items2.to_parquet('D:/escritorio/STEAM/parquet/item.parquet')